### ISSUE TITLE
Validate minimum message length when decoding a message

### ISSUE THREAD

**Issue by besuikerd** [tbsalling/aismessages#27]
Whenever fields of a message are decoded, the `getBits` call can fail whenever the AIS message that was decoded did not meet the expected minimum length of a message with a `StringIndexOutOfBoundsException`. At use site there is also no way to check what the message length is, since this field is private. 

It would be nice to either have access to the message length or have proper validation. I can see there already is a `checkAISMessage` with an empty body

**Comment by tbsalling** [comment]
Thanks, I shall take a look.

Could you provide a failing unit test for `getBits` to demonstrate your point?

**Comment by besuikerd** [comment]
Great! I have a failing testcase on our fork: https://github.com/RotterdamLogisticsLab/aismessages/commit/6bbd7f5a30783f77cb0684beddc868e71d6c0468

**Comment by tbsalling** [comment]
What do you think of this proposed solution (not yet on master)? 
https://github.com/tbsalling/aismessages/commit/1117ab478e25c9b042644176574e11fa452d2f4f

**Comment by tbsalling** [comment]
Yup - it might occur in all messages. Do you have any samples from the wild where the message length for these three is wrong? Otherwise I will have to "invent" some synthetic ones.

**Comment by besuikerd** [comment]
Unfortunately not, for us it only occurred on the binary broadcast messages. It should only fail on the examples i posted above where it is possible to obtain a negative range in the substring call (since `getNumberOfBits` is on the right hand side of the substring call). In other cases it would not give a `StringIndexOutOfBoundsException`, but rather return an empty string I think

**Comment by tbsalling** [comment]
OK - I'll add a simple check to the three messages you mention above.

**Comment by tbsalling** [comment]
Actually - now I recall. This is part of a longer discussion. If you receive an invalid AIS message: Would you like it to be completely rejected due to `checkAISMessage`? Or do you want all the get'ters on th message to work anyway (best effort) - but with isValid = false ?

So far AISmessages has used the latter approach, and I recommend we let it stay that way. Then some fields will still work - but not necessarily all. This can be checked in advance by using "isValid()". At least this is the intention. 

Could you work with that scheme? If yes I will discard my latest commit, and instead work on getting `isValid` try to accomodate the situation you have described.

**Comment by tbsalling** [comment]
And even that is not a true statement. Sigh. I will implement a suggestion which I think addresses you concerns. Stay tuned :-).

**Comment by tbsalling** [comment]
Will HEAD of this branch work for you: https://github.com/tbsalling/aismessages/tree/bugfix/decoding-invalid-short-binary-broadcast-messages ?

**Comment by tbsalling** [comment]
Thanks for your input. The changes are now on master.
