### ISSUE TITLE
Invalid message

### ISSUE THREAD

**Issue by atlesa** [tbsalling/aismessages#38]
Having trouble with this vessel-generated message:
!AIVDM,1,1,,B,H3m9T21HTe<H`u8B22222222220,0*0F

Code:
---
        String msg = "!AIVDM,1,1,,B,H3m9T21HTe<H`u8B22222222220,0*0F";
        NMEAMessage nmeaMessage = NMEAMessage.fromString(msg);
        AISMessage aisMessage = AISMessage.create(nmeaMessage);

---

I get this exception from AISMessage.create():
dk.tbsalling.aismessages.nmea.exceptions.InvalidMessage: Message of type ClassBCSStaticDataReport should be exactly 158, 160 or 168 bits long; not 162. Assumed sourceMmsi: 257057800.

**Comment by tbsalling** [comment]
Hmm... according to the specification (https://www.itu.int/dms_pubrec/itu-r/rec/m/R-REC-M.1371-5-201402-I!!PDF-E.pdf - section 3.22) messages of type 24 should be either 160 or 168 bits long. 162 is not an option - so as such I would say that the message is invalid.

To dig a bit further, we can look at the string in as bits:

H3m9T21HTe<H`u8B22222222220 = 
011000000011110101001001100100000010000001011000100100101101001100011000101000111101001000010010000010000010000010000010000010000010000010000010000010000010000000

If we split the first 40 bits into fields, we get:

011000 = 24 (message type 24 - OK)
00 = 0 (repeat indicator 0 = default - OK)
001111010100100110010000001000 = 257057800 (MMSI 257057800 - OK)
00 = 00 (part number 0; indicates Part A)

Since part number is 0, this message carries part A. I.e. the next 120 bits are the vessel name:

010110001001001011010011000110001010001111010010000100100000100000100000100000100000100000100000100000100000100000100000 = "VIKSFJORD           "

This also looks OK.

So - I would say that the transmitter has "accidentally" added to trailing 0-bits with the message. This is not in accordance with the spec.

I think it is fair that AISmesssages detects and complains about this - but we could perhaps make AISmessages more "tolerant" and only issue a warning - not throw an exception in this case.
