### ISSUE TITLE
Course Over Ground valued 511

### ISSUE THREAD

**Issue by panoet** [tbsalling/aismessages#46]
Is it possible that this library produce Course Over Ground with value 511?

I found that values in my application, checked all logic and found nothing incorect in my code.

As far as I know, value 511 is only valid in Heading Sensor (true heading) data, which mean "no heading sensor". It is not applied to course over ground. CMIIW

**Comment by tbsalling** [comment]
Yes, that is possible. AISmessages is a protocol-level library, it does not assume anything about the data it decodes or how the application will interprete them.

You are right about the ITU-1371 spec. It does not mention 511 as a special meaning for COG. But in real life, in my experience, you can expect to see all sort of strange things. Do not expect all real-life AIS messages to be in strict compliance with the specification - because they are not. Far from actually.

If you have a valid AIS message, with validated checksum, then yes - you can see COG 511 even if that is not mentioned in the specification. 511 is what was sent.
