### ISSUE TITLE
Lots of Error Processing Fragmented Message

### ISSUE THREAD

**Issue by panoet** [tbsalling/aismessages#50]
I received a lot of error when handling fragmented message e.g.:
Oct 13, 2022 8:58:30 AM dk.tbsalling.aismessages.nmea.NMEAMessageInputStreamReader run
WARNING: Received invalid AIS message: "\g:2-2-6291*51\!AIVDM,2,2,3,,88888888HsgOPl58Tp60lt8ThF0000000,2*3C"
Oct 13, 2022 8:58:38 AM dk.tbsalling.aismessages.nmea.NMEAMessageInputStreamReader run
WARNING: Received invalid AIS message: "\g:2-2-6333*58\!AIVDM,2,2,5,,0s1,0*20"
Oct 13, 2022 9:00:01 AM dk.tbsalling.aismessages.nmea.NMEAMessageInputStreamReader run
WARNING: Received invalid AIS message: "\g:2-2-6902*50\!AIVDM,2,2,4,,Q@000018HsFfgP017JvRt0g@u:MOwp0PSm,2*4A"
Oct 13, 2022 9:00:12 AM dk.tbsalling.aismessages.nmea.NMEAMessageInputStreamReader run
WARNING: Received invalid AIS message: "\g:2-2-6967*53\!AIVDM,2,2,9,,00000008Ht6P?P3`7JO5J0cld;F?vJ0PS2,2*5B"
Oct 13, 2022 9:00:14 AM dk.tbsalling.aismessages.nmea.NMEAMessageInputStreamReader run
WARNING: Received invalid AIS message: "\g:2-2-6994*5F\!AIVDM,2,2,6,,ng60gHnm2D;p2d<O,0*6A"

I guess the API cannot find the first fragment. Any suggestion where I have to start analysing the code?

**Comment by tbsalling** [comment]
It is because of the leading  `\g:2-2-629151` possibly because the strings are not NMEA compliant - the should have an asterisk instead of a comma in front of the checksum (`,0*02`, not `,25B`).

Have a look at the latest commit (commit cd95042a468019df93d71bc809a5f6efb7bb0747) - maybe it can solve the situation for you. With this commit you can supply a function serving as a NMEA string preprocessor to the `AisInputStreamReader` - like this:

```java
Function<String, String> nmeaPreProcessor = s -> {
    String t = s;

    int i = s.indexOf("!");
    if (i >= 0) {
        t = s.substring(i);
    }

    return t;
};
new AISInputStreamReader(nmeaInputStream, nmeaPreProcessor, aisMessage -> update(aisMessage)).run()
```

If you play with this `nmeaPreProcessor` I think it can solve your problem.

**Comment by panoet** [comment]
Actually it is GitHub who removes the NMEATagBlok and * from my post. 

Here example of invalid sentence : \g:2-2-3446*58\!AIVDM,2,2,1,,88000000000000000,2*64
